// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: create_group_request.proto

package win.liyufan.im.proto;

public final class CreateGroupRequestOuterClass {
  private CreateGroupRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreateGroupRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.CreateGroupRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.Group group = 1;</code>
     */
    boolean hasGroup();
    /**
     * <code>.proto.Group group = 1;</code>
     */
    win.liyufan.im.proto.GroupOuterClass.Group getGroup();
    /**
     * <code>.proto.Group group = 1;</code>
     */
    win.liyufan.im.proto.GroupOuterClass.GroupOrBuilder getGroupOrBuilder();

    /**
     * <code>.proto.MessageContent notify_content = 2;</code>
     */
    boolean hasNotifyContent();
    /**
     * <code>.proto.MessageContent notify_content = 2;</code>
     */
    win.liyufan.im.proto.MessageContentOuterClass.MessageContent getNotifyContent();
    /**
     * <code>.proto.MessageContent notify_content = 2;</code>
     */
    win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder getNotifyContentOrBuilder();
  }
  /**
   * Protobuf type {@code proto.CreateGroupRequest}
   */
  public  static final class CreateGroupRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.CreateGroupRequest)
      CreateGroupRequestOrBuilder {
    // Use CreateGroupRequest.newBuilder() to construct.
    private CreateGroupRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateGroupRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CreateGroupRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              win.liyufan.im.proto.GroupOuterClass.Group.Builder subBuilder = null;
              if (group_ != null) {
                subBuilder = group_.toBuilder();
              }
              group_ = input.readMessage(win.liyufan.im.proto.GroupOuterClass.Group.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(group_);
                group_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder subBuilder = null;
              if (notifyContent_ != null) {
                subBuilder = notifyContent_.toBuilder();
              }
              notifyContent_ = input.readMessage(win.liyufan.im.proto.MessageContentOuterClass.MessageContent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(notifyContent_);
                notifyContent_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return win.liyufan.im.proto.CreateGroupRequestOuterClass.internal_static_proto_CreateGroupRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return win.liyufan.im.proto.CreateGroupRequestOuterClass.internal_static_proto_CreateGroupRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest.class, win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest.Builder.class);
    }

    public static final int GROUP_FIELD_NUMBER = 1;
    private win.liyufan.im.proto.GroupOuterClass.Group group_;
    /**
     * <code>.proto.Group group = 1;</code>
     */
    public boolean hasGroup() {
      return group_ != null;
    }
    /**
     * <code>.proto.Group group = 1;</code>
     */
    public win.liyufan.im.proto.GroupOuterClass.Group getGroup() {
      return group_ == null ? win.liyufan.im.proto.GroupOuterClass.Group.getDefaultInstance() : group_;
    }
    /**
     * <code>.proto.Group group = 1;</code>
     */
    public win.liyufan.im.proto.GroupOuterClass.GroupOrBuilder getGroupOrBuilder() {
      return getGroup();
    }

    public static final int NOTIFY_CONTENT_FIELD_NUMBER = 2;
    private win.liyufan.im.proto.MessageContentOuterClass.MessageContent notifyContent_;
    /**
     * <code>.proto.MessageContent notify_content = 2;</code>
     */
    public boolean hasNotifyContent() {
      return notifyContent_ != null;
    }
    /**
     * <code>.proto.MessageContent notify_content = 2;</code>
     */
    public win.liyufan.im.proto.MessageContentOuterClass.MessageContent getNotifyContent() {
      return notifyContent_ == null ? win.liyufan.im.proto.MessageContentOuterClass.MessageContent.getDefaultInstance() : notifyContent_;
    }
    /**
     * <code>.proto.MessageContent notify_content = 2;</code>
     */
    public win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder getNotifyContentOrBuilder() {
      return getNotifyContent();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (group_ != null) {
        output.writeMessage(1, getGroup());
      }
      if (notifyContent_ != null) {
        output.writeMessage(2, getNotifyContent());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (group_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGroup());
      }
      if (notifyContent_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getNotifyContent());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest)) {
        return super.equals(obj);
      }
      win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest other = (win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest) obj;

      boolean result = true;
      result = result && (hasGroup() == other.hasGroup());
      if (hasGroup()) {
        result = result && getGroup()
            .equals(other.getGroup());
      }
      result = result && (hasNotifyContent() == other.hasNotifyContent());
      if (hasNotifyContent()) {
        result = result && getNotifyContent()
            .equals(other.getNotifyContent());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGroup()) {
        hash = (37 * hash) + GROUP_FIELD_NUMBER;
        hash = (53 * hash) + getGroup().hashCode();
      }
      if (hasNotifyContent()) {
        hash = (37 * hash) + NOTIFY_CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getNotifyContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.CreateGroupRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.CreateGroupRequest)
        win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return win.liyufan.im.proto.CreateGroupRequestOuterClass.internal_static_proto_CreateGroupRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return win.liyufan.im.proto.CreateGroupRequestOuterClass.internal_static_proto_CreateGroupRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest.class, win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest.Builder.class);
      }

      // Construct using win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (groupBuilder_ == null) {
          group_ = null;
        } else {
          group_ = null;
          groupBuilder_ = null;
        }
        if (notifyContentBuilder_ == null) {
          notifyContent_ = null;
        } else {
          notifyContent_ = null;
          notifyContentBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return win.liyufan.im.proto.CreateGroupRequestOuterClass.internal_static_proto_CreateGroupRequest_descriptor;
      }

      public win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest getDefaultInstanceForType() {
        return win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest.getDefaultInstance();
      }

      public win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest build() {
        win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest buildPartial() {
        win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest result = new win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest(this);
        if (groupBuilder_ == null) {
          result.group_ = group_;
        } else {
          result.group_ = groupBuilder_.build();
        }
        if (notifyContentBuilder_ == null) {
          result.notifyContent_ = notifyContent_;
        } else {
          result.notifyContent_ = notifyContentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest) {
          return mergeFrom((win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest other) {
        if (other == win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest.getDefaultInstance()) return this;
        if (other.hasGroup()) {
          mergeGroup(other.getGroup());
        }
        if (other.hasNotifyContent()) {
          mergeNotifyContent(other.getNotifyContent());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private win.liyufan.im.proto.GroupOuterClass.Group group_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          win.liyufan.im.proto.GroupOuterClass.Group, win.liyufan.im.proto.GroupOuterClass.Group.Builder, win.liyufan.im.proto.GroupOuterClass.GroupOrBuilder> groupBuilder_;
      /**
       * <code>.proto.Group group = 1;</code>
       */
      public boolean hasGroup() {
        return groupBuilder_ != null || group_ != null;
      }
      /**
       * <code>.proto.Group group = 1;</code>
       */
      public win.liyufan.im.proto.GroupOuterClass.Group getGroup() {
        if (groupBuilder_ == null) {
          return group_ == null ? win.liyufan.im.proto.GroupOuterClass.Group.getDefaultInstance() : group_;
        } else {
          return groupBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Group group = 1;</code>
       */
      public Builder setGroup(win.liyufan.im.proto.GroupOuterClass.Group value) {
        if (groupBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          group_ = value;
          onChanged();
        } else {
          groupBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.Group group = 1;</code>
       */
      public Builder setGroup(
          win.liyufan.im.proto.GroupOuterClass.Group.Builder builderForValue) {
        if (groupBuilder_ == null) {
          group_ = builderForValue.build();
          onChanged();
        } else {
          groupBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.Group group = 1;</code>
       */
      public Builder mergeGroup(win.liyufan.im.proto.GroupOuterClass.Group value) {
        if (groupBuilder_ == null) {
          if (group_ != null) {
            group_ =
              win.liyufan.im.proto.GroupOuterClass.Group.newBuilder(group_).mergeFrom(value).buildPartial();
          } else {
            group_ = value;
          }
          onChanged();
        } else {
          groupBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.Group group = 1;</code>
       */
      public Builder clearGroup() {
        if (groupBuilder_ == null) {
          group_ = null;
          onChanged();
        } else {
          group_ = null;
          groupBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.Group group = 1;</code>
       */
      public win.liyufan.im.proto.GroupOuterClass.Group.Builder getGroupBuilder() {
        
        onChanged();
        return getGroupFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Group group = 1;</code>
       */
      public win.liyufan.im.proto.GroupOuterClass.GroupOrBuilder getGroupOrBuilder() {
        if (groupBuilder_ != null) {
          return groupBuilder_.getMessageOrBuilder();
        } else {
          return group_ == null ?
              win.liyufan.im.proto.GroupOuterClass.Group.getDefaultInstance() : group_;
        }
      }
      /**
       * <code>.proto.Group group = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          win.liyufan.im.proto.GroupOuterClass.Group, win.liyufan.im.proto.GroupOuterClass.Group.Builder, win.liyufan.im.proto.GroupOuterClass.GroupOrBuilder> 
          getGroupFieldBuilder() {
        if (groupBuilder_ == null) {
          groupBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              win.liyufan.im.proto.GroupOuterClass.Group, win.liyufan.im.proto.GroupOuterClass.Group.Builder, win.liyufan.im.proto.GroupOuterClass.GroupOrBuilder>(
                  getGroup(),
                  getParentForChildren(),
                  isClean());
          group_ = null;
        }
        return groupBuilder_;
      }

      private win.liyufan.im.proto.MessageContentOuterClass.MessageContent notifyContent_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          win.liyufan.im.proto.MessageContentOuterClass.MessageContent, win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder, win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder> notifyContentBuilder_;
      /**
       * <code>.proto.MessageContent notify_content = 2;</code>
       */
      public boolean hasNotifyContent() {
        return notifyContentBuilder_ != null || notifyContent_ != null;
      }
      /**
       * <code>.proto.MessageContent notify_content = 2;</code>
       */
      public win.liyufan.im.proto.MessageContentOuterClass.MessageContent getNotifyContent() {
        if (notifyContentBuilder_ == null) {
          return notifyContent_ == null ? win.liyufan.im.proto.MessageContentOuterClass.MessageContent.getDefaultInstance() : notifyContent_;
        } else {
          return notifyContentBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.MessageContent notify_content = 2;</code>
       */
      public Builder setNotifyContent(win.liyufan.im.proto.MessageContentOuterClass.MessageContent value) {
        if (notifyContentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          notifyContent_ = value;
          onChanged();
        } else {
          notifyContentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.MessageContent notify_content = 2;</code>
       */
      public Builder setNotifyContent(
          win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder builderForValue) {
        if (notifyContentBuilder_ == null) {
          notifyContent_ = builderForValue.build();
          onChanged();
        } else {
          notifyContentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.MessageContent notify_content = 2;</code>
       */
      public Builder mergeNotifyContent(win.liyufan.im.proto.MessageContentOuterClass.MessageContent value) {
        if (notifyContentBuilder_ == null) {
          if (notifyContent_ != null) {
            notifyContent_ =
              win.liyufan.im.proto.MessageContentOuterClass.MessageContent.newBuilder(notifyContent_).mergeFrom(value).buildPartial();
          } else {
            notifyContent_ = value;
          }
          onChanged();
        } else {
          notifyContentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.MessageContent notify_content = 2;</code>
       */
      public Builder clearNotifyContent() {
        if (notifyContentBuilder_ == null) {
          notifyContent_ = null;
          onChanged();
        } else {
          notifyContent_ = null;
          notifyContentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.MessageContent notify_content = 2;</code>
       */
      public win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder getNotifyContentBuilder() {
        
        onChanged();
        return getNotifyContentFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.MessageContent notify_content = 2;</code>
       */
      public win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder getNotifyContentOrBuilder() {
        if (notifyContentBuilder_ != null) {
          return notifyContentBuilder_.getMessageOrBuilder();
        } else {
          return notifyContent_ == null ?
              win.liyufan.im.proto.MessageContentOuterClass.MessageContent.getDefaultInstance() : notifyContent_;
        }
      }
      /**
       * <code>.proto.MessageContent notify_content = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          win.liyufan.im.proto.MessageContentOuterClass.MessageContent, win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder, win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder> 
          getNotifyContentFieldBuilder() {
        if (notifyContentBuilder_ == null) {
          notifyContentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              win.liyufan.im.proto.MessageContentOuterClass.MessageContent, win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder, win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder>(
                  getNotifyContent(),
                  getParentForChildren(),
                  isClean());
          notifyContent_ = null;
        }
        return notifyContentBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.CreateGroupRequest)
    }

    // @@protoc_insertion_point(class_scope:proto.CreateGroupRequest)
    private static final win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest();
    }

    public static win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateGroupRequest>
        PARSER = new com.google.protobuf.AbstractParser<CreateGroupRequest>() {
      public CreateGroupRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CreateGroupRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateGroupRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateGroupRequest> getParserForType() {
      return PARSER;
    }

    public win.liyufan.im.proto.CreateGroupRequestOuterClass.CreateGroupRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CreateGroupRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CreateGroupRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032create_group_request.proto\022\005proto\032\013gro" +
      "up.proto\032\025message_content.proto\"`\n\022Creat" +
      "eGroupRequest\022\033\n\005group\030\001 \001(\0132\014.proto.Gro" +
      "up\022-\n\016notify_content\030\002 \001(\0132\025.proto.Messa" +
      "geContentB4\n\024win.liyufan.im.protoB\034Creat" +
      "eGroupRequestOuterClassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          win.liyufan.im.proto.GroupOuterClass.getDescriptor(),
          win.liyufan.im.proto.MessageContentOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_CreateGroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_CreateGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CreateGroupRequest_descriptor,
        new java.lang.String[] { "Group", "NotifyContent", });
    win.liyufan.im.proto.GroupOuterClass.getDescriptor();
    win.liyufan.im.proto.MessageContentOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
