// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pull_message_result.proto

package win.liyufan.im.proto;

public final class PullMessageResultOuterClass {
  private PullMessageResultOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PullMessageResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PullMessageResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.Message message = 1;</code>
     */
    java.util.List<win.liyufan.im.proto.MessageOuterClass.Message> 
        getMessageList();
    /**
     * <code>repeated .proto.Message message = 1;</code>
     */
    win.liyufan.im.proto.MessageOuterClass.Message getMessage(int index);
    /**
     * <code>repeated .proto.Message message = 1;</code>
     */
    int getMessageCount();
    /**
     * <code>repeated .proto.Message message = 1;</code>
     */
    java.util.List<? extends win.liyufan.im.proto.MessageOuterClass.MessageOrBuilder> 
        getMessageOrBuilderList();
    /**
     * <code>repeated .proto.Message message = 1;</code>
     */
    win.liyufan.im.proto.MessageOuterClass.MessageOrBuilder getMessageOrBuilder(
        int index);

    /**
     * <code>int64 current = 2;</code>
     */
    long getCurrent();

    /**
     * <code>int64 head = 3;</code>
     */
    long getHead();
  }
  /**
   * Protobuf type {@code proto.PullMessageResult}
   */
  public  static final class PullMessageResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.PullMessageResult)
      PullMessageResultOrBuilder {
    // Use PullMessageResult.newBuilder() to construct.
    private PullMessageResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PullMessageResult() {
      message_ = java.util.Collections.emptyList();
      current_ = 0L;
      head_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PullMessageResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                message_ = new java.util.ArrayList<win.liyufan.im.proto.MessageOuterClass.Message>();
                mutable_bitField0_ |= 0x00000001;
              }
              message_.add(
                  input.readMessage(win.liyufan.im.proto.MessageOuterClass.Message.parser(), extensionRegistry));
              break;
            }
            case 16: {

              current_ = input.readInt64();
              break;
            }
            case 24: {

              head_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          message_ = java.util.Collections.unmodifiableList(message_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return win.liyufan.im.proto.PullMessageResultOuterClass.internal_static_proto_PullMessageResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return win.liyufan.im.proto.PullMessageResultOuterClass.internal_static_proto_PullMessageResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult.class, win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult.Builder.class);
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private java.util.List<win.liyufan.im.proto.MessageOuterClass.Message> message_;
    /**
     * <code>repeated .proto.Message message = 1;</code>
     */
    public java.util.List<win.liyufan.im.proto.MessageOuterClass.Message> getMessageList() {
      return message_;
    }
    /**
     * <code>repeated .proto.Message message = 1;</code>
     */
    public java.util.List<? extends win.liyufan.im.proto.MessageOuterClass.MessageOrBuilder> 
        getMessageOrBuilderList() {
      return message_;
    }
    /**
     * <code>repeated .proto.Message message = 1;</code>
     */
    public int getMessageCount() {
      return message_.size();
    }
    /**
     * <code>repeated .proto.Message message = 1;</code>
     */
    public win.liyufan.im.proto.MessageOuterClass.Message getMessage(int index) {
      return message_.get(index);
    }
    /**
     * <code>repeated .proto.Message message = 1;</code>
     */
    public win.liyufan.im.proto.MessageOuterClass.MessageOrBuilder getMessageOrBuilder(
        int index) {
      return message_.get(index);
    }

    public static final int CURRENT_FIELD_NUMBER = 2;
    private long current_;
    /**
     * <code>int64 current = 2;</code>
     */
    public long getCurrent() {
      return current_;
    }

    public static final int HEAD_FIELD_NUMBER = 3;
    private long head_;
    /**
     * <code>int64 head = 3;</code>
     */
    public long getHead() {
      return head_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < message_.size(); i++) {
        output.writeMessage(1, message_.get(i));
      }
      if (current_ != 0L) {
        output.writeInt64(2, current_);
      }
      if (head_ != 0L) {
        output.writeInt64(3, head_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < message_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, message_.get(i));
      }
      if (current_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, current_);
      }
      if (head_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, head_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult)) {
        return super.equals(obj);
      }
      win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult other = (win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult) obj;

      boolean result = true;
      result = result && getMessageList()
          .equals(other.getMessageList());
      result = result && (getCurrent()
          == other.getCurrent());
      result = result && (getHead()
          == other.getHead());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMessageCount() > 0) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessageList().hashCode();
      }
      hash = (37 * hash) + CURRENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCurrent());
      hash = (37 * hash) + HEAD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHead());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PullMessageResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PullMessageResult)
        win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return win.liyufan.im.proto.PullMessageResultOuterClass.internal_static_proto_PullMessageResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return win.liyufan.im.proto.PullMessageResultOuterClass.internal_static_proto_PullMessageResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult.class, win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult.Builder.class);
      }

      // Construct using win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMessageFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (messageBuilder_ == null) {
          message_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          messageBuilder_.clear();
        }
        current_ = 0L;

        head_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return win.liyufan.im.proto.PullMessageResultOuterClass.internal_static_proto_PullMessageResult_descriptor;
      }

      public win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult getDefaultInstanceForType() {
        return win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult.getDefaultInstance();
      }

      public win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult build() {
        win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult buildPartial() {
        win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult result = new win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            message_ = java.util.Collections.unmodifiableList(message_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
        result.current_ = current_;
        result.head_ = head_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult) {
          return mergeFrom((win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult other) {
        if (other == win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult.getDefaultInstance()) return this;
        if (messageBuilder_ == null) {
          if (!other.message_.isEmpty()) {
            if (message_.isEmpty()) {
              message_ = other.message_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessageIsMutable();
              message_.addAll(other.message_);
            }
            onChanged();
          }
        } else {
          if (!other.message_.isEmpty()) {
            if (messageBuilder_.isEmpty()) {
              messageBuilder_.dispose();
              messageBuilder_ = null;
              message_ = other.message_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMessageFieldBuilder() : null;
            } else {
              messageBuilder_.addAllMessages(other.message_);
            }
          }
        }
        if (other.getCurrent() != 0L) {
          setCurrent(other.getCurrent());
        }
        if (other.getHead() != 0L) {
          setHead(other.getHead());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<win.liyufan.im.proto.MessageOuterClass.Message> message_ =
        java.util.Collections.emptyList();
      private void ensureMessageIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          message_ = new java.util.ArrayList<win.liyufan.im.proto.MessageOuterClass.Message>(message_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          win.liyufan.im.proto.MessageOuterClass.Message, win.liyufan.im.proto.MessageOuterClass.Message.Builder, win.liyufan.im.proto.MessageOuterClass.MessageOrBuilder> messageBuilder_;

      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public java.util.List<win.liyufan.im.proto.MessageOuterClass.Message> getMessageList() {
        if (messageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(message_);
        } else {
          return messageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public int getMessageCount() {
        if (messageBuilder_ == null) {
          return message_.size();
        } else {
          return messageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public win.liyufan.im.proto.MessageOuterClass.Message getMessage(int index) {
        if (messageBuilder_ == null) {
          return message_.get(index);
        } else {
          return messageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public Builder setMessage(
          int index, win.liyufan.im.proto.MessageOuterClass.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.set(index, value);
          onChanged();
        } else {
          messageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public Builder setMessage(
          int index, win.liyufan.im.proto.MessageOuterClass.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.set(index, builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public Builder addMessage(win.liyufan.im.proto.MessageOuterClass.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.add(value);
          onChanged();
        } else {
          messageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public Builder addMessage(
          int index, win.liyufan.im.proto.MessageOuterClass.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.add(index, value);
          onChanged();
        } else {
          messageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public Builder addMessage(
          win.liyufan.im.proto.MessageOuterClass.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.add(builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public Builder addMessage(
          int index, win.liyufan.im.proto.MessageOuterClass.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.add(index, builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public Builder addAllMessage(
          java.lang.Iterable<? extends win.liyufan.im.proto.MessageOuterClass.Message> values) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, message_);
          onChanged();
        } else {
          messageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public Builder removeMessage(int index) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.remove(index);
          onChanged();
        } else {
          messageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public win.liyufan.im.proto.MessageOuterClass.Message.Builder getMessageBuilder(
          int index) {
        return getMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public win.liyufan.im.proto.MessageOuterClass.MessageOrBuilder getMessageOrBuilder(
          int index) {
        if (messageBuilder_ == null) {
          return message_.get(index);  } else {
          return messageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public java.util.List<? extends win.liyufan.im.proto.MessageOuterClass.MessageOrBuilder> 
           getMessageOrBuilderList() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(message_);
        }
      }
      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public win.liyufan.im.proto.MessageOuterClass.Message.Builder addMessageBuilder() {
        return getMessageFieldBuilder().addBuilder(
            win.liyufan.im.proto.MessageOuterClass.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public win.liyufan.im.proto.MessageOuterClass.Message.Builder addMessageBuilder(
          int index) {
        return getMessageFieldBuilder().addBuilder(
            index, win.liyufan.im.proto.MessageOuterClass.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Message message = 1;</code>
       */
      public java.util.List<win.liyufan.im.proto.MessageOuterClass.Message.Builder> 
           getMessageBuilderList() {
        return getMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          win.liyufan.im.proto.MessageOuterClass.Message, win.liyufan.im.proto.MessageOuterClass.Message.Builder, win.liyufan.im.proto.MessageOuterClass.MessageOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              win.liyufan.im.proto.MessageOuterClass.Message, win.liyufan.im.proto.MessageOuterClass.Message.Builder, win.liyufan.im.proto.MessageOuterClass.MessageOrBuilder>(
                  message_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }

      private long current_ ;
      /**
       * <code>int64 current = 2;</code>
       */
      public long getCurrent() {
        return current_;
      }
      /**
       * <code>int64 current = 2;</code>
       */
      public Builder setCurrent(long value) {
        
        current_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 current = 2;</code>
       */
      public Builder clearCurrent() {
        
        current_ = 0L;
        onChanged();
        return this;
      }

      private long head_ ;
      /**
       * <code>int64 head = 3;</code>
       */
      public long getHead() {
        return head_;
      }
      /**
       * <code>int64 head = 3;</code>
       */
      public Builder setHead(long value) {
        
        head_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 head = 3;</code>
       */
      public Builder clearHead() {
        
        head_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.PullMessageResult)
    }

    // @@protoc_insertion_point(class_scope:proto.PullMessageResult)
    private static final win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult();
    }

    public static win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PullMessageResult>
        PARSER = new com.google.protobuf.AbstractParser<PullMessageResult>() {
      public PullMessageResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PullMessageResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PullMessageResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PullMessageResult> getParserForType() {
      return PARSER;
    }

    public win.liyufan.im.proto.PullMessageResultOuterClass.PullMessageResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PullMessageResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PullMessageResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031pull_message_result.proto\022\005proto\032\rmess" +
      "age.proto\"S\n\021PullMessageResult\022\037\n\007messag" +
      "e\030\001 \003(\0132\016.proto.Message\022\017\n\007current\030\002 \001(\003" +
      "\022\014\n\004head\030\003 \001(\003B3\n\024win.liyufan.im.protoB\033" +
      "PullMessageResultOuterClassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          win.liyufan.im.proto.MessageOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_PullMessageResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_PullMessageResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PullMessageResult_descriptor,
        new java.lang.String[] { "Message", "Current", "Head", });
    win.liyufan.im.proto.MessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
