// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: id_list_buf.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "id_list_buf.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace mars {
namespace stn {
class IDListBufDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<IDListBuf> {
} _IDListBuf_default_instance_;

namespace protobuf_id_5flist_5fbuf_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IDListBuf, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IDListBuf, id_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(IDListBuf)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_IDListBuf_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "id_list_buf.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _IDListBuf_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _IDListBuf_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\021id_list_buf.proto\022\010mars.stn\"\027\n\tIDListB"
      "uf\022\n\n\002id\030\001 \003(\tB+\n\024win.liyufan.im.protoB\023"
      "IDListBufOuterClassb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 107);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "id_list_buf.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_id_5flist_5fbuf_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int IDListBuf::kIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

IDListBuf::IDListBuf()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_id_5flist_5fbuf_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:mars.stn.IDListBuf)
}
IDListBuf::IDListBuf(const IDListBuf& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      id_(from.id_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:mars.stn.IDListBuf)
}

void IDListBuf::SharedCtor() {
  _cached_size_ = 0;
}

IDListBuf::~IDListBuf() {
  // @@protoc_insertion_point(destructor:mars.stn.IDListBuf)
  SharedDtor();
}

void IDListBuf::SharedDtor() {
}

void IDListBuf::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* IDListBuf::descriptor() {
  protobuf_id_5flist_5fbuf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_id_5flist_5fbuf_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const IDListBuf& IDListBuf::default_instance() {
  protobuf_id_5flist_5fbuf_2eproto::InitDefaults();
  return *internal_default_instance();
}

IDListBuf* IDListBuf::New(::google::protobuf::Arena* arena) const {
  IDListBuf* n = new IDListBuf;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void IDListBuf::Clear() {
// @@protoc_insertion_point(message_clear_start:mars.stn.IDListBuf)
  id_.Clear();
}

bool IDListBuf::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mars.stn.IDListBuf)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->id(this->id_size() - 1).data(),
            this->id(this->id_size() - 1).length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "mars.stn.IDListBuf.id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mars.stn.IDListBuf)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mars.stn.IDListBuf)
  return false;
#undef DO_
}

void IDListBuf::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mars.stn.IDListBuf)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string id = 1;
  for (int i = 0, n = this->id_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->id(i).data(), this->id(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mars.stn.IDListBuf.id");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->id(i), output);
  }

  // @@protoc_insertion_point(serialize_end:mars.stn.IDListBuf)
}

::google::protobuf::uint8* IDListBuf::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:mars.stn.IDListBuf)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string id = 1;
  for (int i = 0, n = this->id_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->id(i).data(), this->id(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mars.stn.IDListBuf.id");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->id(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:mars.stn.IDListBuf)
  return target;
}

size_t IDListBuf::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mars.stn.IDListBuf)
  size_t total_size = 0;

  // repeated string id = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->id_size());
  for (int i = 0, n = this->id_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->id(i));
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void IDListBuf::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mars.stn.IDListBuf)
  GOOGLE_DCHECK_NE(&from, this);
  const IDListBuf* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const IDListBuf>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mars.stn.IDListBuf)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mars.stn.IDListBuf)
    MergeFrom(*source);
  }
}

void IDListBuf::MergeFrom(const IDListBuf& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mars.stn.IDListBuf)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  id_.MergeFrom(from.id_);
}

void IDListBuf::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mars.stn.IDListBuf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void IDListBuf::CopyFrom(const IDListBuf& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mars.stn.IDListBuf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IDListBuf::IsInitialized() const {
  return true;
}

void IDListBuf::Swap(IDListBuf* other) {
  if (other == this) return;
  InternalSwap(other);
}
void IDListBuf::InternalSwap(IDListBuf* other) {
  id_.InternalSwap(&other->id_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata IDListBuf::GetMetadata() const {
  protobuf_id_5flist_5fbuf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_id_5flist_5fbuf_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// IDListBuf

// repeated string id = 1;
int IDListBuf::id_size() const {
  return id_.size();
}
void IDListBuf::clear_id() {
  id_.Clear();
}
const ::std::string& IDListBuf::id(int index) const {
  // @@protoc_insertion_point(field_get:mars.stn.IDListBuf.id)
  return id_.Get(index);
}
::std::string* IDListBuf::mutable_id(int index) {
  // @@protoc_insertion_point(field_mutable:mars.stn.IDListBuf.id)
  return id_.Mutable(index);
}
void IDListBuf::set_id(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:mars.stn.IDListBuf.id)
  id_.Mutable(index)->assign(value);
}
#if LANG_CXX11
void IDListBuf::set_id(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:mars.stn.IDListBuf.id)
  id_.Mutable(index)->assign(std::move(value));
}
#endif
void IDListBuf::set_id(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  id_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:mars.stn.IDListBuf.id)
}
void IDListBuf::set_id(int index, const char* value, size_t size) {
  id_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:mars.stn.IDListBuf.id)
}
::std::string* IDListBuf::add_id() {
  // @@protoc_insertion_point(field_add_mutable:mars.stn.IDListBuf.id)
  return id_.Add();
}
void IDListBuf::add_id(const ::std::string& value) {
  id_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:mars.stn.IDListBuf.id)
}
#if LANG_CXX11
void IDListBuf::add_id(::std::string&& value) {
  id_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:mars.stn.IDListBuf.id)
}
#endif
void IDListBuf::add_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  id_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:mars.stn.IDListBuf.id)
}
void IDListBuf::add_id(const char* value, size_t size) {
  id_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:mars.stn.IDListBuf.id)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
IDListBuf::id() const {
  // @@protoc_insertion_point(field_list:mars.stn.IDListBuf.id)
  return id_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
IDListBuf::mutable_id() {
  // @@protoc_insertion_point(field_mutable_list:mars.stn.IDListBuf.id)
  return &id_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace stn
}  // namespace mars

// @@protoc_insertion_point(global_scope)
