// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: id_list_buf.proto

#ifndef PROTOBUF_id_5flist_5fbuf_2eproto__INCLUDED
#define PROTOBUF_id_5flist_5fbuf_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace mars {
namespace stn {
class IDListBuf;
class IDListBufDefaultTypeInternal;
extern IDListBufDefaultTypeInternal _IDListBuf_default_instance_;
}  // namespace stn
}  // namespace mars

namespace mars {
namespace stn {

namespace protobuf_id_5flist_5fbuf_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_id_5flist_5fbuf_2eproto

// ===================================================================

class IDListBuf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mars.stn.IDListBuf) */ {
 public:
  IDListBuf();
  virtual ~IDListBuf();

  IDListBuf(const IDListBuf& from);

  inline IDListBuf& operator=(const IDListBuf& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IDListBuf& default_instance();

  static inline const IDListBuf* internal_default_instance() {
    return reinterpret_cast<const IDListBuf*>(
               &_IDListBuf_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(IDListBuf* other);

  // implements Message ----------------------------------------------

  inline IDListBuf* New() const PROTOBUF_FINAL { return New(NULL); }

  IDListBuf* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const IDListBuf& from);
  void MergeFrom(const IDListBuf& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(IDListBuf* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string id = 1;
  int id_size() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id(int index) const;
  ::std::string* mutable_id(int index);
  void set_id(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_id(int index, ::std::string&& value);
  #endif
  void set_id(int index, const char* value);
  void set_id(int index, const char* value, size_t size);
  ::std::string* add_id();
  void add_id(const ::std::string& value);
  #if LANG_CXX11
  void add_id(::std::string&& value);
  #endif
  void add_id(const char* value);
  void add_id(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& id() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_id();

  // @@protoc_insertion_point(class_scope:mars.stn.IDListBuf)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> id_;
  mutable int _cached_size_;
  friend struct protobuf_id_5flist_5fbuf_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// IDListBuf

// repeated string id = 1;
inline int IDListBuf::id_size() const {
  return id_.size();
}
inline void IDListBuf::clear_id() {
  id_.Clear();
}
inline const ::std::string& IDListBuf::id(int index) const {
  // @@protoc_insertion_point(field_get:mars.stn.IDListBuf.id)
  return id_.Get(index);
}
inline ::std::string* IDListBuf::mutable_id(int index) {
  // @@protoc_insertion_point(field_mutable:mars.stn.IDListBuf.id)
  return id_.Mutable(index);
}
inline void IDListBuf::set_id(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:mars.stn.IDListBuf.id)
  id_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void IDListBuf::set_id(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:mars.stn.IDListBuf.id)
  id_.Mutable(index)->assign(std::move(value));
}
#endif
inline void IDListBuf::set_id(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  id_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:mars.stn.IDListBuf.id)
}
inline void IDListBuf::set_id(int index, const char* value, size_t size) {
  id_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:mars.stn.IDListBuf.id)
}
inline ::std::string* IDListBuf::add_id() {
  // @@protoc_insertion_point(field_add_mutable:mars.stn.IDListBuf.id)
  return id_.Add();
}
inline void IDListBuf::add_id(const ::std::string& value) {
  id_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:mars.stn.IDListBuf.id)
}
#if LANG_CXX11
inline void IDListBuf::add_id(::std::string&& value) {
  id_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:mars.stn.IDListBuf.id)
}
#endif
inline void IDListBuf::add_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  id_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:mars.stn.IDListBuf.id)
}
inline void IDListBuf::add_id(const char* value, size_t size) {
  id_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:mars.stn.IDListBuf.id)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
IDListBuf::id() const {
  // @@protoc_insertion_point(field_list:mars.stn.IDListBuf.id)
  return id_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
IDListBuf::mutable_id() {
  // @@protoc_insertion_point(field_mutable_list:mars.stn.IDListBuf.id)
  return &id_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace stn
}  // namespace mars

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_id_5flist_5fbuf_2eproto__INCLUDED
