// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modify_group_info_request.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "modify_group_info_request.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace mars {
namespace stn {
class ModifyGroupInfoRequestDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ModifyGroupInfoRequest> {
} _ModifyGroupInfoRequest_default_instance_;

namespace protobuf_modify_5fgroup_5finfo_5frequest_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModifyGroupInfoRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModifyGroupInfoRequest, group_info_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModifyGroupInfoRequest, to_line_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModifyGroupInfoRequest, notify_content_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(ModifyGroupInfoRequest)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_ModifyGroupInfoRequest_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "modify_group_info_request.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _ModifyGroupInfoRequest_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::mars::stn::protobuf_group_2eproto::InitDefaults();
  ::mars::stn::protobuf_message_5fcontent_2eproto::InitDefaults();
  _ModifyGroupInfoRequest_default_instance_.DefaultConstruct();
  _ModifyGroupInfoRequest_default_instance_.get_mutable()->group_info_ = const_cast< ::mars::stn::GroupInfo*>(
      ::mars::stn::GroupInfo::internal_default_instance());
  _ModifyGroupInfoRequest_default_instance_.get_mutable()->notify_content_ = const_cast< ::mars::stn::MessageContent*>(
      ::mars::stn::MessageContent::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\037modify_group_info_request.proto\022\010mars."
      "stn\032\013group.proto\032\025message_content.proto\""
      "\204\001\n\026ModifyGroupInfoRequest\022\'\n\ngroup_info"
      "\030\001 \001(\0132\023.mars.stn.GroupInfo\022\017\n\007to_line\030\002"
      " \003(\005\0220\n\016notify_content\030\003 \001(\0132\030.mars.stn."
      "MessageContentB8\n\024win.liyufan.im.protoB "
      "ModifyGroupInfoRequestOuterClassb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 280);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "modify_group_info_request.proto", &protobuf_RegisterTypes);
  ::mars::stn::protobuf_group_2eproto::AddDescriptors();
  ::mars::stn::protobuf_message_5fcontent_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_modify_5fgroup_5finfo_5frequest_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ModifyGroupInfoRequest::kGroupInfoFieldNumber;
const int ModifyGroupInfoRequest::kToLineFieldNumber;
const int ModifyGroupInfoRequest::kNotifyContentFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ModifyGroupInfoRequest::ModifyGroupInfoRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_modify_5fgroup_5finfo_5frequest_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:mars.stn.ModifyGroupInfoRequest)
}
ModifyGroupInfoRequest::ModifyGroupInfoRequest(const ModifyGroupInfoRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      to_line_(from.to_line_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_group_info()) {
    group_info_ = new ::mars::stn::GroupInfo(*from.group_info_);
  } else {
    group_info_ = NULL;
  }
  if (from.has_notify_content()) {
    notify_content_ = new ::mars::stn::MessageContent(*from.notify_content_);
  } else {
    notify_content_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:mars.stn.ModifyGroupInfoRequest)
}

void ModifyGroupInfoRequest::SharedCtor() {
  ::memset(&group_info_, 0, reinterpret_cast<char*>(&notify_content_) -
    reinterpret_cast<char*>(&group_info_) + sizeof(notify_content_));
  _cached_size_ = 0;
}

ModifyGroupInfoRequest::~ModifyGroupInfoRequest() {
  // @@protoc_insertion_point(destructor:mars.stn.ModifyGroupInfoRequest)
  SharedDtor();
}

void ModifyGroupInfoRequest::SharedDtor() {
  if (this != internal_default_instance()) {
    delete group_info_;
  }
  if (this != internal_default_instance()) {
    delete notify_content_;
  }
}

void ModifyGroupInfoRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ModifyGroupInfoRequest::descriptor() {
  protobuf_modify_5fgroup_5finfo_5frequest_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_modify_5fgroup_5finfo_5frequest_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ModifyGroupInfoRequest& ModifyGroupInfoRequest::default_instance() {
  protobuf_modify_5fgroup_5finfo_5frequest_2eproto::InitDefaults();
  return *internal_default_instance();
}

ModifyGroupInfoRequest* ModifyGroupInfoRequest::New(::google::protobuf::Arena* arena) const {
  ModifyGroupInfoRequest* n = new ModifyGroupInfoRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ModifyGroupInfoRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mars.stn.ModifyGroupInfoRequest)
  to_line_.Clear();
  if (GetArenaNoVirtual() == NULL && group_info_ != NULL) {
    delete group_info_;
  }
  group_info_ = NULL;
  if (GetArenaNoVirtual() == NULL && notify_content_ != NULL) {
    delete notify_content_;
  }
  notify_content_ = NULL;
}

bool ModifyGroupInfoRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mars.stn.ModifyGroupInfoRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .mars.stn.GroupInfo group_info = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_group_info()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 to_line = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_to_line())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) ==
                   static_cast< ::google::protobuf::uint8>(16u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 18u, input, this->mutable_to_line())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .mars.stn.MessageContent notify_content = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_notify_content()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mars.stn.ModifyGroupInfoRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mars.stn.ModifyGroupInfoRequest)
  return false;
#undef DO_
}

void ModifyGroupInfoRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mars.stn.ModifyGroupInfoRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .mars.stn.GroupInfo group_info = 1;
  if (this->has_group_info()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->group_info_, output);
  }

  // repeated int32 to_line = 2;
  if (this->to_line_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_to_line_cached_byte_size_);
  }
  for (int i = 0, n = this->to_line_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->to_line(i), output);
  }

  // .mars.stn.MessageContent notify_content = 3;
  if (this->has_notify_content()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->notify_content_, output);
  }

  // @@protoc_insertion_point(serialize_end:mars.stn.ModifyGroupInfoRequest)
}

::google::protobuf::uint8* ModifyGroupInfoRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:mars.stn.ModifyGroupInfoRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .mars.stn.GroupInfo group_info = 1;
  if (this->has_group_info()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->group_info_, deterministic, target);
  }

  // repeated int32 to_line = 2;
  if (this->to_line_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      2,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _to_line_cached_byte_size_, target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->to_line_, target);
  }

  // .mars.stn.MessageContent notify_content = 3;
  if (this->has_notify_content()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->notify_content_, deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:mars.stn.ModifyGroupInfoRequest)
  return target;
}

size_t ModifyGroupInfoRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mars.stn.ModifyGroupInfoRequest)
  size_t total_size = 0;

  // repeated int32 to_line = 2;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->to_line_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _to_line_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // .mars.stn.GroupInfo group_info = 1;
  if (this->has_group_info()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->group_info_);
  }

  // .mars.stn.MessageContent notify_content = 3;
  if (this->has_notify_content()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->notify_content_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ModifyGroupInfoRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mars.stn.ModifyGroupInfoRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ModifyGroupInfoRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ModifyGroupInfoRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mars.stn.ModifyGroupInfoRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mars.stn.ModifyGroupInfoRequest)
    MergeFrom(*source);
  }
}

void ModifyGroupInfoRequest::MergeFrom(const ModifyGroupInfoRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mars.stn.ModifyGroupInfoRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  to_line_.MergeFrom(from.to_line_);
  if (from.has_group_info()) {
    mutable_group_info()->::mars::stn::GroupInfo::MergeFrom(from.group_info());
  }
  if (from.has_notify_content()) {
    mutable_notify_content()->::mars::stn::MessageContent::MergeFrom(from.notify_content());
  }
}

void ModifyGroupInfoRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mars.stn.ModifyGroupInfoRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ModifyGroupInfoRequest::CopyFrom(const ModifyGroupInfoRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mars.stn.ModifyGroupInfoRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ModifyGroupInfoRequest::IsInitialized() const {
  return true;
}

void ModifyGroupInfoRequest::Swap(ModifyGroupInfoRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ModifyGroupInfoRequest::InternalSwap(ModifyGroupInfoRequest* other) {
  to_line_.InternalSwap(&other->to_line_);
  std::swap(group_info_, other->group_info_);
  std::swap(notify_content_, other->notify_content_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ModifyGroupInfoRequest::GetMetadata() const {
  protobuf_modify_5fgroup_5finfo_5frequest_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_modify_5fgroup_5finfo_5frequest_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ModifyGroupInfoRequest

// .mars.stn.GroupInfo group_info = 1;
bool ModifyGroupInfoRequest::has_group_info() const {
  return this != internal_default_instance() && group_info_ != NULL;
}
void ModifyGroupInfoRequest::clear_group_info() {
  if (GetArenaNoVirtual() == NULL && group_info_ != NULL) delete group_info_;
  group_info_ = NULL;
}
const ::mars::stn::GroupInfo& ModifyGroupInfoRequest::group_info() const {
  // @@protoc_insertion_point(field_get:mars.stn.ModifyGroupInfoRequest.group_info)
  return group_info_ != NULL ? *group_info_
                         : *::mars::stn::GroupInfo::internal_default_instance();
}
::mars::stn::GroupInfo* ModifyGroupInfoRequest::mutable_group_info() {
  
  if (group_info_ == NULL) {
    group_info_ = new ::mars::stn::GroupInfo;
  }
  // @@protoc_insertion_point(field_mutable:mars.stn.ModifyGroupInfoRequest.group_info)
  return group_info_;
}
::mars::stn::GroupInfo* ModifyGroupInfoRequest::release_group_info() {
  // @@protoc_insertion_point(field_release:mars.stn.ModifyGroupInfoRequest.group_info)
  
  ::mars::stn::GroupInfo* temp = group_info_;
  group_info_ = NULL;
  return temp;
}
void ModifyGroupInfoRequest::set_allocated_group_info(::mars::stn::GroupInfo* group_info) {
  delete group_info_;
  group_info_ = group_info;
  if (group_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:mars.stn.ModifyGroupInfoRequest.group_info)
}

// repeated int32 to_line = 2;
int ModifyGroupInfoRequest::to_line_size() const {
  return to_line_.size();
}
void ModifyGroupInfoRequest::clear_to_line() {
  to_line_.Clear();
}
::google::protobuf::int32 ModifyGroupInfoRequest::to_line(int index) const {
  // @@protoc_insertion_point(field_get:mars.stn.ModifyGroupInfoRequest.to_line)
  return to_line_.Get(index);
}
void ModifyGroupInfoRequest::set_to_line(int index, ::google::protobuf::int32 value) {
  to_line_.Set(index, value);
  // @@protoc_insertion_point(field_set:mars.stn.ModifyGroupInfoRequest.to_line)
}
void ModifyGroupInfoRequest::add_to_line(::google::protobuf::int32 value) {
  to_line_.Add(value);
  // @@protoc_insertion_point(field_add:mars.stn.ModifyGroupInfoRequest.to_line)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ModifyGroupInfoRequest::to_line() const {
  // @@protoc_insertion_point(field_list:mars.stn.ModifyGroupInfoRequest.to_line)
  return to_line_;
}
::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ModifyGroupInfoRequest::mutable_to_line() {
  // @@protoc_insertion_point(field_mutable_list:mars.stn.ModifyGroupInfoRequest.to_line)
  return &to_line_;
}

// .mars.stn.MessageContent notify_content = 3;
bool ModifyGroupInfoRequest::has_notify_content() const {
  return this != internal_default_instance() && notify_content_ != NULL;
}
void ModifyGroupInfoRequest::clear_notify_content() {
  if (GetArenaNoVirtual() == NULL && notify_content_ != NULL) delete notify_content_;
  notify_content_ = NULL;
}
const ::mars::stn::MessageContent& ModifyGroupInfoRequest::notify_content() const {
  // @@protoc_insertion_point(field_get:mars.stn.ModifyGroupInfoRequest.notify_content)
  return notify_content_ != NULL ? *notify_content_
                         : *::mars::stn::MessageContent::internal_default_instance();
}
::mars::stn::MessageContent* ModifyGroupInfoRequest::mutable_notify_content() {
  
  if (notify_content_ == NULL) {
    notify_content_ = new ::mars::stn::MessageContent;
  }
  // @@protoc_insertion_point(field_mutable:mars.stn.ModifyGroupInfoRequest.notify_content)
  return notify_content_;
}
::mars::stn::MessageContent* ModifyGroupInfoRequest::release_notify_content() {
  // @@protoc_insertion_point(field_release:mars.stn.ModifyGroupInfoRequest.notify_content)
  
  ::mars::stn::MessageContent* temp = notify_content_;
  notify_content_ = NULL;
  return temp;
}
void ModifyGroupInfoRequest::set_allocated_notify_content(::mars::stn::MessageContent* notify_content) {
  delete notify_content_;
  notify_content_ = notify_content;
  if (notify_content) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:mars.stn.ModifyGroupInfoRequest.notify_content)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace stn
}  // namespace mars

// @@protoc_insertion_point(global_scope)
