// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pull_user_response.proto

#ifndef PROTOBUF_pull_5fuser_5fresponse_2eproto__INCLUDED
#define PROTOBUF_pull_5fuser_5fresponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "user.pb.h"
// @@protoc_insertion_point(includes)
namespace mars {
namespace stn {
class PullUserResult;
class PullUserResultDefaultTypeInternal;
extern PullUserResultDefaultTypeInternal _PullUserResult_default_instance_;
class User;
class UserDefaultTypeInternal;
extern UserDefaultTypeInternal _User_default_instance_;
class UserResult;
class UserResultDefaultTypeInternal;
extern UserResultDefaultTypeInternal _UserResult_default_instance_;
}  // namespace stn
}  // namespace mars

namespace mars {
namespace stn {

namespace protobuf_pull_5fuser_5fresponse_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_pull_5fuser_5fresponse_2eproto

enum UserResultCode {
  Success = 0,
  NotFound = 1,
  NotModified = 2,
  UserResultCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  UserResultCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool UserResultCode_IsValid(int value);
const UserResultCode UserResultCode_MIN = Success;
const UserResultCode UserResultCode_MAX = NotModified;
const int UserResultCode_ARRAYSIZE = UserResultCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* UserResultCode_descriptor();
inline const ::std::string& UserResultCode_Name(UserResultCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    UserResultCode_descriptor(), value);
}
inline bool UserResultCode_Parse(
    const ::std::string& name, UserResultCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UserResultCode>(
    UserResultCode_descriptor(), name, value);
}
// ===================================================================

class UserResult : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mars.stn.UserResult) */ {
 public:
  UserResult();
  virtual ~UserResult();

  UserResult(const UserResult& from);

  inline UserResult& operator=(const UserResult& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserResult& default_instance();

  static inline const UserResult* internal_default_instance() {
    return reinterpret_cast<const UserResult*>(
               &_UserResult_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(UserResult* other);

  // implements Message ----------------------------------------------

  inline UserResult* New() const PROTOBUF_FINAL { return New(NULL); }

  UserResult* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UserResult& from);
  void MergeFrom(const UserResult& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UserResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .mars.stn.User user = 1;
  bool has_user() const;
  void clear_user();
  static const int kUserFieldNumber = 1;
  const ::mars::stn::User& user() const;
  ::mars::stn::User* mutable_user();
  ::mars::stn::User* release_user();
  void set_allocated_user(::mars::stn::User* user);

  // .mars.stn.UserResultCode code = 2;
  void clear_code();
  static const int kCodeFieldNumber = 2;
  ::mars::stn::UserResultCode code() const;
  void set_code(::mars::stn::UserResultCode value);

  // @@protoc_insertion_point(class_scope:mars.stn.UserResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::mars::stn::User* user_;
  int code_;
  mutable int _cached_size_;
  friend struct protobuf_pull_5fuser_5fresponse_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PullUserResult : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mars.stn.PullUserResult) */ {
 public:
  PullUserResult();
  virtual ~PullUserResult();

  PullUserResult(const PullUserResult& from);

  inline PullUserResult& operator=(const PullUserResult& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PullUserResult& default_instance();

  static inline const PullUserResult* internal_default_instance() {
    return reinterpret_cast<const PullUserResult*>(
               &_PullUserResult_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(PullUserResult* other);

  // implements Message ----------------------------------------------

  inline PullUserResult* New() const PROTOBUF_FINAL { return New(NULL); }

  PullUserResult* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PullUserResult& from);
  void MergeFrom(const PullUserResult& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PullUserResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .mars.stn.UserResult result = 1;
  int result_size() const;
  void clear_result();
  static const int kResultFieldNumber = 1;
  const ::mars::stn::UserResult& result(int index) const;
  ::mars::stn::UserResult* mutable_result(int index);
  ::mars::stn::UserResult* add_result();
  ::google::protobuf::RepeatedPtrField< ::mars::stn::UserResult >*
      mutable_result();
  const ::google::protobuf::RepeatedPtrField< ::mars::stn::UserResult >&
      result() const;

  // @@protoc_insertion_point(class_scope:mars.stn.PullUserResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::mars::stn::UserResult > result_;
  mutable int _cached_size_;
  friend struct protobuf_pull_5fuser_5fresponse_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// UserResult

// .mars.stn.User user = 1;
inline bool UserResult::has_user() const {
  return this != internal_default_instance() && user_ != NULL;
}
inline void UserResult::clear_user() {
  if (GetArenaNoVirtual() == NULL && user_ != NULL) delete user_;
  user_ = NULL;
}
inline const ::mars::stn::User& UserResult::user() const {
  // @@protoc_insertion_point(field_get:mars.stn.UserResult.user)
  return user_ != NULL ? *user_
                         : *::mars::stn::User::internal_default_instance();
}
inline ::mars::stn::User* UserResult::mutable_user() {
  
  if (user_ == NULL) {
    user_ = new ::mars::stn::User;
  }
  // @@protoc_insertion_point(field_mutable:mars.stn.UserResult.user)
  return user_;
}
inline ::mars::stn::User* UserResult::release_user() {
  // @@protoc_insertion_point(field_release:mars.stn.UserResult.user)
  
  ::mars::stn::User* temp = user_;
  user_ = NULL;
  return temp;
}
inline void UserResult::set_allocated_user(::mars::stn::User* user) {
  delete user_;
  user_ = user;
  if (user) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:mars.stn.UserResult.user)
}

// .mars.stn.UserResultCode code = 2;
inline void UserResult::clear_code() {
  code_ = 0;
}
inline ::mars::stn::UserResultCode UserResult::code() const {
  // @@protoc_insertion_point(field_get:mars.stn.UserResult.code)
  return static_cast< ::mars::stn::UserResultCode >(code_);
}
inline void UserResult::set_code(::mars::stn::UserResultCode value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:mars.stn.UserResult.code)
}

// -------------------------------------------------------------------

// PullUserResult

// repeated .mars.stn.UserResult result = 1;
inline int PullUserResult::result_size() const {
  return result_.size();
}
inline void PullUserResult::clear_result() {
  result_.Clear();
}
inline const ::mars::stn::UserResult& PullUserResult::result(int index) const {
  // @@protoc_insertion_point(field_get:mars.stn.PullUserResult.result)
  return result_.Get(index);
}
inline ::mars::stn::UserResult* PullUserResult::mutable_result(int index) {
  // @@protoc_insertion_point(field_mutable:mars.stn.PullUserResult.result)
  return result_.Mutable(index);
}
inline ::mars::stn::UserResult* PullUserResult::add_result() {
  // @@protoc_insertion_point(field_add:mars.stn.PullUserResult.result)
  return result_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::mars::stn::UserResult >*
PullUserResult::mutable_result() {
  // @@protoc_insertion_point(field_mutable_list:mars.stn.PullUserResult.result)
  return &result_;
}
inline const ::google::protobuf::RepeatedPtrField< ::mars::stn::UserResult >&
PullUserResult::result() const {
  // @@protoc_insertion_point(field_list:mars.stn.PullUserResult.result)
  return result_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace stn
}  // namespace mars

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::mars::stn::UserResultCode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mars::stn::UserResultCode>() {
  return ::mars::stn::UserResultCode_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pull_5fuser_5fresponse_2eproto__INCLUDED
