// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remove_group_member_request.proto

#ifndef PROTOBUF_remove_5fgroup_5fmember_5frequest_2eproto__INCLUDED
#define PROTOBUF_remove_5fgroup_5fmember_5frequest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "message_content.pb.h"
// @@protoc_insertion_point(includes)
namespace mars {
namespace stn {
class MessageContent;
class MessageContentDefaultTypeInternal;
extern MessageContentDefaultTypeInternal _MessageContent_default_instance_;
class RemoveGroupMemberRequest;
class RemoveGroupMemberRequestDefaultTypeInternal;
extern RemoveGroupMemberRequestDefaultTypeInternal _RemoveGroupMemberRequest_default_instance_;
}  // namespace stn
}  // namespace mars

namespace mars {
namespace stn {

namespace protobuf_remove_5fgroup_5fmember_5frequest_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_remove_5fgroup_5fmember_5frequest_2eproto

// ===================================================================

class RemoveGroupMemberRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mars.stn.RemoveGroupMemberRequest) */ {
 public:
  RemoveGroupMemberRequest();
  virtual ~RemoveGroupMemberRequest();

  RemoveGroupMemberRequest(const RemoveGroupMemberRequest& from);

  inline RemoveGroupMemberRequest& operator=(const RemoveGroupMemberRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RemoveGroupMemberRequest& default_instance();

  static inline const RemoveGroupMemberRequest* internal_default_instance() {
    return reinterpret_cast<const RemoveGroupMemberRequest*>(
               &_RemoveGroupMemberRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(RemoveGroupMemberRequest* other);

  // implements Message ----------------------------------------------

  inline RemoveGroupMemberRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  RemoveGroupMemberRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RemoveGroupMemberRequest& from);
  void MergeFrom(const RemoveGroupMemberRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RemoveGroupMemberRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string removed_member = 2;
  int removed_member_size() const;
  void clear_removed_member();
  static const int kRemovedMemberFieldNumber = 2;
  const ::std::string& removed_member(int index) const;
  ::std::string* mutable_removed_member(int index);
  void set_removed_member(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_removed_member(int index, ::std::string&& value);
  #endif
  void set_removed_member(int index, const char* value);
  void set_removed_member(int index, const char* value, size_t size);
  ::std::string* add_removed_member();
  void add_removed_member(const ::std::string& value);
  #if LANG_CXX11
  void add_removed_member(::std::string&& value);
  #endif
  void add_removed_member(const char* value);
  void add_removed_member(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& removed_member() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_removed_member();

  // repeated int32 to_line = 3;
  int to_line_size() const;
  void clear_to_line();
  static const int kToLineFieldNumber = 3;
  ::google::protobuf::int32 to_line(int index) const;
  void set_to_line(int index, ::google::protobuf::int32 value);
  void add_to_line(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      to_line() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_to_line();

  // string group_id = 1;
  void clear_group_id();
  static const int kGroupIdFieldNumber = 1;
  const ::std::string& group_id() const;
  void set_group_id(const ::std::string& value);
  #if LANG_CXX11
  void set_group_id(::std::string&& value);
  #endif
  void set_group_id(const char* value);
  void set_group_id(const char* value, size_t size);
  ::std::string* mutable_group_id();
  ::std::string* release_group_id();
  void set_allocated_group_id(::std::string* group_id);

  // .mars.stn.MessageContent notify_content = 4;
  bool has_notify_content() const;
  void clear_notify_content();
  static const int kNotifyContentFieldNumber = 4;
  const ::mars::stn::MessageContent& notify_content() const;
  ::mars::stn::MessageContent* mutable_notify_content();
  ::mars::stn::MessageContent* release_notify_content();
  void set_allocated_notify_content(::mars::stn::MessageContent* notify_content);

  // @@protoc_insertion_point(class_scope:mars.stn.RemoveGroupMemberRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> removed_member_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > to_line_;
  mutable int _to_line_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr group_id_;
  ::mars::stn::MessageContent* notify_content_;
  mutable int _cached_size_;
  friend struct protobuf_remove_5fgroup_5fmember_5frequest_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// RemoveGroupMemberRequest

// string group_id = 1;
inline void RemoveGroupMemberRequest::clear_group_id() {
  group_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RemoveGroupMemberRequest::group_id() const {
  // @@protoc_insertion_point(field_get:mars.stn.RemoveGroupMemberRequest.group_id)
  return group_id_.GetNoArena();
}
inline void RemoveGroupMemberRequest::set_group_id(const ::std::string& value) {
  
  group_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mars.stn.RemoveGroupMemberRequest.group_id)
}
#if LANG_CXX11
inline void RemoveGroupMemberRequest::set_group_id(::std::string&& value) {
  
  group_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mars.stn.RemoveGroupMemberRequest.group_id)
}
#endif
inline void RemoveGroupMemberRequest::set_group_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  group_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mars.stn.RemoveGroupMemberRequest.group_id)
}
inline void RemoveGroupMemberRequest::set_group_id(const char* value, size_t size) {
  
  group_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mars.stn.RemoveGroupMemberRequest.group_id)
}
inline ::std::string* RemoveGroupMemberRequest::mutable_group_id() {
  
  // @@protoc_insertion_point(field_mutable:mars.stn.RemoveGroupMemberRequest.group_id)
  return group_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RemoveGroupMemberRequest::release_group_id() {
  // @@protoc_insertion_point(field_release:mars.stn.RemoveGroupMemberRequest.group_id)
  
  return group_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RemoveGroupMemberRequest::set_allocated_group_id(::std::string* group_id) {
  if (group_id != NULL) {
    
  } else {
    
  }
  group_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), group_id);
  // @@protoc_insertion_point(field_set_allocated:mars.stn.RemoveGroupMemberRequest.group_id)
}

// repeated string removed_member = 2;
inline int RemoveGroupMemberRequest::removed_member_size() const {
  return removed_member_.size();
}
inline void RemoveGroupMemberRequest::clear_removed_member() {
  removed_member_.Clear();
}
inline const ::std::string& RemoveGroupMemberRequest::removed_member(int index) const {
  // @@protoc_insertion_point(field_get:mars.stn.RemoveGroupMemberRequest.removed_member)
  return removed_member_.Get(index);
}
inline ::std::string* RemoveGroupMemberRequest::mutable_removed_member(int index) {
  // @@protoc_insertion_point(field_mutable:mars.stn.RemoveGroupMemberRequest.removed_member)
  return removed_member_.Mutable(index);
}
inline void RemoveGroupMemberRequest::set_removed_member(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:mars.stn.RemoveGroupMemberRequest.removed_member)
  removed_member_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void RemoveGroupMemberRequest::set_removed_member(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:mars.stn.RemoveGroupMemberRequest.removed_member)
  removed_member_.Mutable(index)->assign(std::move(value));
}
#endif
inline void RemoveGroupMemberRequest::set_removed_member(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  removed_member_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:mars.stn.RemoveGroupMemberRequest.removed_member)
}
inline void RemoveGroupMemberRequest::set_removed_member(int index, const char* value, size_t size) {
  removed_member_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:mars.stn.RemoveGroupMemberRequest.removed_member)
}
inline ::std::string* RemoveGroupMemberRequest::add_removed_member() {
  // @@protoc_insertion_point(field_add_mutable:mars.stn.RemoveGroupMemberRequest.removed_member)
  return removed_member_.Add();
}
inline void RemoveGroupMemberRequest::add_removed_member(const ::std::string& value) {
  removed_member_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:mars.stn.RemoveGroupMemberRequest.removed_member)
}
#if LANG_CXX11
inline void RemoveGroupMemberRequest::add_removed_member(::std::string&& value) {
  removed_member_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:mars.stn.RemoveGroupMemberRequest.removed_member)
}
#endif
inline void RemoveGroupMemberRequest::add_removed_member(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  removed_member_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:mars.stn.RemoveGroupMemberRequest.removed_member)
}
inline void RemoveGroupMemberRequest::add_removed_member(const char* value, size_t size) {
  removed_member_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:mars.stn.RemoveGroupMemberRequest.removed_member)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
RemoveGroupMemberRequest::removed_member() const {
  // @@protoc_insertion_point(field_list:mars.stn.RemoveGroupMemberRequest.removed_member)
  return removed_member_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
RemoveGroupMemberRequest::mutable_removed_member() {
  // @@protoc_insertion_point(field_mutable_list:mars.stn.RemoveGroupMemberRequest.removed_member)
  return &removed_member_;
}

// repeated int32 to_line = 3;
inline int RemoveGroupMemberRequest::to_line_size() const {
  return to_line_.size();
}
inline void RemoveGroupMemberRequest::clear_to_line() {
  to_line_.Clear();
}
inline ::google::protobuf::int32 RemoveGroupMemberRequest::to_line(int index) const {
  // @@protoc_insertion_point(field_get:mars.stn.RemoveGroupMemberRequest.to_line)
  return to_line_.Get(index);
}
inline void RemoveGroupMemberRequest::set_to_line(int index, ::google::protobuf::int32 value) {
  to_line_.Set(index, value);
  // @@protoc_insertion_point(field_set:mars.stn.RemoveGroupMemberRequest.to_line)
}
inline void RemoveGroupMemberRequest::add_to_line(::google::protobuf::int32 value) {
  to_line_.Add(value);
  // @@protoc_insertion_point(field_add:mars.stn.RemoveGroupMemberRequest.to_line)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
RemoveGroupMemberRequest::to_line() const {
  // @@protoc_insertion_point(field_list:mars.stn.RemoveGroupMemberRequest.to_line)
  return to_line_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
RemoveGroupMemberRequest::mutable_to_line() {
  // @@protoc_insertion_point(field_mutable_list:mars.stn.RemoveGroupMemberRequest.to_line)
  return &to_line_;
}

// .mars.stn.MessageContent notify_content = 4;
inline bool RemoveGroupMemberRequest::has_notify_content() const {
  return this != internal_default_instance() && notify_content_ != NULL;
}
inline void RemoveGroupMemberRequest::clear_notify_content() {
  if (GetArenaNoVirtual() == NULL && notify_content_ != NULL) delete notify_content_;
  notify_content_ = NULL;
}
inline const ::mars::stn::MessageContent& RemoveGroupMemberRequest::notify_content() const {
  // @@protoc_insertion_point(field_get:mars.stn.RemoveGroupMemberRequest.notify_content)
  return notify_content_ != NULL ? *notify_content_
                         : *::mars::stn::MessageContent::internal_default_instance();
}
inline ::mars::stn::MessageContent* RemoveGroupMemberRequest::mutable_notify_content() {
  
  if (notify_content_ == NULL) {
    notify_content_ = new ::mars::stn::MessageContent;
  }
  // @@protoc_insertion_point(field_mutable:mars.stn.RemoveGroupMemberRequest.notify_content)
  return notify_content_;
}
inline ::mars::stn::MessageContent* RemoveGroupMemberRequest::release_notify_content() {
  // @@protoc_insertion_point(field_release:mars.stn.RemoveGroupMemberRequest.notify_content)
  
  ::mars::stn::MessageContent* temp = notify_content_;
  notify_content_ = NULL;
  return temp;
}
inline void RemoveGroupMemberRequest::set_allocated_notify_content(::mars::stn::MessageContent* notify_content) {
  delete notify_content_;
  notify_content_ = notify_content;
  if (notify_content) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:mars.stn.RemoveGroupMemberRequest.notify_content)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace stn
}  // namespace mars

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_remove_5fgroup_5fmember_5frequest_2eproto__INCLUDED
