// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_content.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ContentType

typedef GPB_ENUM(ContentType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ContentType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ContentType_Text = 0,
  ContentType_Image = 1,
  ContentType_Voice = 2,
  ContentType_Location = 3,
  ContentType_Video = 4,
  ContentType_RichMedia = 5,
  ContentType_Custom = 6,
};

GPBEnumDescriptor *ContentType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ContentType_IsValidValue(int32_t value);

#pragma mark - MessageContentRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MessageContentRoot : GPBRootObject
@end

#pragma mark - MessageContent

typedef GPB_ENUM(MessageContent_FieldNumber) {
  MessageContent_FieldNumber_Type = 1,
  MessageContent_FieldNumber_SearchableContent = 2,
  MessageContent_FieldNumber_PushContent = 3,
  MessageContent_FieldNumber_Data_p = 4,
};

@interface MessageContent : GPBMessage

@property(nonatomic, readwrite) ContentType type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *searchableContent;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pushContent;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@end

/**
 * Fetches the raw value of a @c MessageContent's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t MessageContent_Type_RawValue(MessageContent *message);
/**
 * Sets the raw value of an @c MessageContent's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetMessageContent_Type_RawValue(MessageContent *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
